version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=storydb
    networks:
      - fabelfabrik-network

networks:
  fabelfabrik-network:
    driver: bridge

volumes:
  mongodb_data: